services:
  dentalgo-bi:
    build: .
    ports:
      - "3035:3000"
    environment:
      - AUTH_TRUST_HOST=true
    env_file:
      - .env.local
    volumes:
      - ./prisma_data:/app/prisma_data
    restart: always
    container_name: dentalgo-bi
